export const TOURNAMENT_CLOSED = "TOURNAMENT_CLOSED" as const;
export const TOURNAMENT_FULL = "TOURNAMENT_FULL" as const;
export const NOT_REGISTERED = "NOT_REGISTERED" as const;
export const TOURNAMENT_NOT_CANCELLABLE = "TOURNAMENT_NOT_CANCELLABLE" as const;
export const INSUFFICIENT_BANKROLL = "INSUFFICIENT_BANKROLL" as const;
export const TOURNAMENT_NOT_REGISTERED = "TOURNAMENT_NOT_REGISTERED" as const;
export const TOURNAMENT_JOIN_CLOSED = "TOURNAMENT_JOIN_CLOSED" as const;

export const TOURNAMENT_CLIENT_ERRORS = new Set<string>([
  INSUFFICIENT_BANKROLL,
  TOURNAMENT_CLOSED,
  TOURNAMENT_FULL,
  NOT_REGISTERED,
  TOURNAMENT_NOT_CANCELLABLE,
  TOURNAMENT_NOT_REGISTERED,
  TOURNAMENT_JOIN_CLOSED,
]);
