export const TOURNAMENT_CLOSED = "TOURNAMENT_CLOSED" as const;
export const TOURNAMENT_REBUY_NOT_ALLOWED = "TOURNAMENT_REBUY_NOT_ALLOWED" as const;
export const TOURNAMENT_FULL = "TOURNAMENT_FULL" as const;
export const NOT_REGISTERED = "NOT_REGISTERED" as const;
export const TOURNAMENT_NOT_CANCELLABLE = "TOURNAMENT_NOT_CANCELLABLE" as const;
export const TOURNAMENT_CANCEL_FORBIDDEN = "TOURNAMENT_CANCEL_FORBIDDEN" as const;
export const TOURNAMENT_HAS_REGISTRATIONS = "TOURNAMENT_HAS_REGISTRATIONS" as const;
export const INSUFFICIENT_BANKROLL = "INSUFFICIENT_BANKROLL" as const;
export const TOURNAMENT_NOT_REGISTERED = "TOURNAMENT_NOT_REGISTERED" as const;
export const TOURNAMENT_JOIN_CLOSED = "TOURNAMENT_JOIN_CLOSED" as const;
export const TOURNAMENT_AWAITING_PLAYERS = "TOURNAMENT_AWAITING_PLAYERS" as const;
export const TOURNAMENT_TABLE_UNAVAILABLE = "TOURNAMENT_TABLE_UNAVAILABLE" as const;
export const TOURNAMENT_SPECTATOR_READONLY = "TOURNAMENT_SPECTATOR_READONLY" as const;
export const TOURNAMENT_START_IN_PAST = "TOURNAMENT_START_IN_PAST" as const;
export const TOURNAMENT_REBUY_CONFIG_INVALID = "TOURNAMENT_REBUY_CONFIG_INVALID" as const;
export const TOURNAMENT_NOT_REBUY_PENDING = "TOURNAMENT_NOT_REBUY_PENDING" as const;

export const TOURNAMENT_CLIENT_ERRORS = new Set<string>([
  INSUFFICIENT_BANKROLL,
  TOURNAMENT_CLOSED,
  TOURNAMENT_FULL,
  NOT_REGISTERED,
  TOURNAMENT_NOT_CANCELLABLE,
  TOURNAMENT_CANCEL_FORBIDDEN,
  TOURNAMENT_HAS_REGISTRATIONS,
  TOURNAMENT_NOT_REGISTERED,
  TOURNAMENT_JOIN_CLOSED,
  TOURNAMENT_SPECTATOR_READONLY,
  TOURNAMENT_REBUY_NOT_ALLOWED,
  TOURNAMENT_AWAITING_PLAYERS,
  TOURNAMENT_TABLE_UNAVAILABLE,
  TOURNAMENT_START_IN_PAST,
  TOURNAMENT_REBUY_CONFIG_INVALID,
  TOURNAMENT_NOT_REBUY_PENDING,
]);
