/** Tailwind: token-driven theme + namespaced ui- component classes */

module.exports = {
  presets: [require("nativewind/preset")],
  /* Required for react-native-css-interop: allows manual color scheme; use html className="dark" in +html.tsx */
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "hsl(var(--c-bg, 0 0% 5%) / <alpha-value>)",
        panel: "hsl(var(--c-panel, 0 0% 9%) / <alpha-value>)",
        "panel-elevated": "hsl(var(--c-panel-elevated, 0 0% 12%) / <alpha-value>)",
        border: "hsl(var(--c-border, 0 0% 18%) / <alpha-value>)",
        "border-subtle": "hsl(var(--c-border-subtle, 0 0% 14%) / <alpha-value>)",
        edge: "hsl(var(--c-edge, 0 0% 14%) / <alpha-value>)",
        text: "hsl(var(--c-text, 0 0% 96%) / <alpha-value>)",
        muted: "hsl(var(--c-muted, 0 0% 68%) / <alpha-value>)",
        placeholder: "hsl(var(--c-placeholder, 0 0% 58%) / <alpha-value>)",
        brand: "hsl(var(--c-brand) / <alpha-value>)",
        "brand-soft": "hsl(var(--c-brand-soft) / <alpha-value>)",
        "brand-bright": "hsl(var(--c-brand-bright) / <alpha-value>)",
        gold: "hsl(var(--c-gold) / <alpha-value>)",
        "gold-soft": "hsl(var(--c-gold-soft) / <alpha-value>)",
        danger: "hsl(var(--c-danger) / <alpha-value>)",
        success: "hsl(var(--c-success) / <alpha-value>)",
        warn: "hsl(var(--c-warn) / <alpha-value>)",
        felt: "hsl(var(--c-felt) / <alpha-value>)",
        "card-face": "hsl(var(--c-card-face) / <alpha-value>)",
        "card-back": "hsl(var(--c-card-back) / <alpha-value>)",
        "chip-low": "hsl(var(--c-chip-low) / <alpha-value>)",
        "chip-mid": "hsl(var(--c-chip-mid) / <alpha-value>)",
        "chip-high": "hsl(var(--c-chip-high) / <alpha-value>)",
      },
      spacing: {
        0: "var(--s-0)",
        1: "var(--s-1)",
        2: "var(--s-2)",
        3: "var(--s-3)",
        4: "var(--s-4)",
        5: "var(--s-5)",
        6: "var(--s-6)",
        8: "var(--s-8)",
        10: "var(--s-10)",
        12: "var(--s-12)",
        16: "var(--s-16)",
        20: "var(--s-20)",
        xs: "var(--s-xs)",
        sm: "var(--s-sm)",
        md: "var(--s-md)",
        lg: "var(--s-lg)",
        xl: "var(--s-xl)",
        "2xl": "var(--s-2xl)",
      },
      borderRadius: {
        0: "var(--r-0)",
        1: "var(--r-1)",
        2: "var(--r-2)",
        3: "var(--r-3)",
        4: "var(--r-4)",
        full: "var(--r-full)",
        sm: "var(--r-sm)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
        table: "var(--r-table)",
        card: "var(--r-card)",
      },
    },
  },
  plugins: [
    function ({ addComponents }) {
      addComponents({
        /* Surfaces */
        ".ui-surface": { "@apply rounded-md border border-border-subtle bg-panel": {} },
        ".ui-surface-card": { "@apply rounded-lg border border-border bg-panel-elevated": {} },
        ".ui-surface-overlay": { "@apply rounded-lg border border-border bg-panel-elevated": {} },
        ".ui-surface-elevated": {
          "@apply rounded-lg border border-border border-t border-edge bg-panel-elevated": {},
        },
        /* Typography roles */
        ".ui-text": { "@apply text-text": {} },
        ".ui-muted": { "@apply text-muted": {} },
        ".ui-danger": { "@apply text-danger": {} },
        ".ui-success": { "@apply text-success": {} },
        ".ui-warn": { "@apply text-warn": {} },
        /* Layout primitives */
        ".ui-row": { "@apply flex-row items-center": {} },
        ".ui-row-wrap": { "@apply flex-row flex-wrap items-center": {} },
        ".ui-col": { "@apply flex flex-col": {} },
        ".ui-center": { "@apply items-center justify-center": {} },
        /* Stacks / spacing (on parent) */
        ".ui-stack-1": { "@apply gap-1": {} },
        ".ui-stack-2": { "@apply gap-2": {} },
        ".ui-stack-3": { "@apply gap-3": {} },
        ".ui-stack-4": { "@apply gap-4": {} },
        ".ui-stack-6": { "@apply gap-6": {} },
        ".ui-inline-1": { "@apply gap-1": {} },
        ".ui-inline-2": { "@apply gap-2": {} },
        ".ui-inline-3": { "@apply gap-3": {} },
        ".ui-inline-4": { "@apply gap-4": {} },
        /* Bars */
        ".ui-bottom-bar": { "@apply border-t border-border bg-panel": {} },
        /* Touch targets */
        ".ui-touch": { "@apply min-h-[44px] min-w-[44px] items-center justify-center": {} },
        ".ui-accent-line-b": { "@apply border-b-2 border-gold-soft": {} },
        ".ui-accent-line-t": { "@apply border-t border-edge": {} },
        ".ui-p-inline-2": { "@apply px-2": {} },
        ".ui-p-inline-3": { "@apply px-3": {} },
        ".ui-p-inline-4": { "@apply px-4": {} },
        ".ui-p-inline-lg": { "@apply px-4": {} },
        ".ui-p-stack-1": { "@apply py-1": {} },
        ".ui-p-stack-2": { "@apply py-2": {} },
        ".ui-p-stack-3": { "@apply py-3": {} },
        ".ui-p-stack-4": { "@apply py-4": {} },
        ".ui-p-2": { "@apply p-2": {} },
        ".ui-p-3": { "@apply p-3": {} },
        ".ui-p-4": { "@apply p-4": {} },
        ".ui-p-md": { "@apply p-3": {} },
        ".ui-p-lg": { "@apply p-4": {} },
        ".ui-divider": { "@apply h-px bg-border": {} },
        ".ui-border-b": { "@apply border-b border-border": {} },
        ".ui-border-t": { "@apply border-t border-border": {} },
        ".ui-section": { "@apply border-b border-border px-4 py-3": {} },
        ".ui-section-tight": { "@apply border-b border-border px-4 py-2": {} },
      });
    },
  ],
};
