export const COMMUNITY_CARD_GAP_DESKTOP = 33;
export const COMMUNITY_CARD_GAP_MOBILE = 3;
export const COMMUNITY_BOARD_HEIGHT = 100;
export const COMMUNITY_CARD_SCALE = 1;
export const COMMUNITY_BOARD_HEIGHT_LANDSCAPE = 125;
export const COMMUNITY_CARD_SCALE_LANDSCAPE = 1.5;