export const COMMUNITY_CARD_GAP = 35;
export const COMMUNITY_BOARD_HEIGHT = 150;
export const COMMUNITY_CARD_SCALE = 1.23;
export const COMMUNITY_BOARD_HEIGHT_LANDSCAPE = 116;
export const COMMUNITY_CARD_SCALE_LANDSCAPE = 1.5;