import type { DrillQuestion } from "../types.js";

/**
 * Curated, hand-verified equity-split scenarios. Not randomly generated: real hand ranges
 * produce equity splits that don't land cleanly on a bucket, ties, or misleading edge cases,
 * so this category is authored content rather than a runtime generator.
 *
 * Preflop entries use widely-published all-in equity figures for named archetypes. Flop/turn
 * entries use the rule of 2/4 approximation against a single made hand with no realistic
 * redraw (every out card is checked against the exact cards in play so none are counterfeit).
 */
export const MATCHUP_EQUITY_SCENARIOS: Array<Omit<DrillQuestion, "id">> = [
  // --- Preflop (widely-published approximate all-in equities) ---
  {
    category: "MATCHUP_EQUITY",
    street: "PREFLOP",
    prompt: "AA vs KK",
    heroHand: ["As", "Ah"],
    villainHand: ["Kd", "Kc"],
    options: ["80 / 20", "70 / 30", "60 / 40", "50 / 50"],
    correctIndex: 0,
    explanation: "Big pocket pair vs a smaller pocket pair is a textbook ~80/20 flip preflop.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "PREFLOP",
    prompt: "KK vs 22",
    heroHand: ["Ks", "Kh"],
    villainHand: ["2d", "2c"],
    options: ["80 / 20", "70 / 30", "60 / 40", "50 / 50"],
    correctIndex: 0,
    explanation: "A big pair crushes a tiny pocket pair — still about 80/20 even though 22 is 'live'.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "PREFLOP",
    prompt: "QQ vs AKo",
    heroHand: ["Qs", "Qh"],
    villainHand: ["Ad", "Kc"],
    options: ["60 / 40", "55 / 45", "50 / 50", "45 / 55"],
    correctIndex: 1,
    explanation: "The classic coinflip: QQ is only a small favorite over two overcards, about 54/46.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "PREFLOP",
    prompt: "TT vs AKo",
    heroHand: ["Ts", "Th"],
    villainHand: ["Ad", "Kc"],
    options: ["60 / 40", "55 / 45", "50 / 50", "45 / 55"],
    correctIndex: 1,
    explanation: "Same shape as QQ vs AK — a mid pair vs two overcards is a near coinflip, pair slightly ahead.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "PREFLOP",
    prompt: "22 vs AKo",
    heroHand: ["2s", "2h"],
    villainHand: ["Ad", "Kc"],
    options: ["60 / 40", "55 / 45", "50 / 50", "45 / 55"],
    correctIndex: 2,
    explanation: "Small pocket pair vs two overcards is about as close to 50/50 as preflop spots get.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "PREFLOP",
    prompt: "AKo vs AQo",
    heroHand: ["Ah", "Ks"],
    villainHand: ["Ad", "Qc"],
    options: ["80 / 20", "70 / 30", "60 / 40", "50 / 50"],
    correctIndex: 1,
    explanation: "AK dominates AQ — same top card, better kicker. Roughly 70/30.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "PREFLOP",
    prompt: "AKo vs KQo",
    heroHand: ["Ah", "Ks"],
    villainHand: ["Kd", "Qc"],
    options: ["80 / 20", "70 / 30", "60 / 40", "50 / 50"],
    correctIndex: 1,
    explanation: "AK dominates KQ the same way — shared King, better kicker. About 70/30.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "PREFLOP",
    prompt: "AA vs KQs",
    heroHand: ["Ac", "Ad"],
    villainHand: ["Kh", "Qh"],
    options: ["80 / 20", "70 / 30", "60 / 40", "50 / 50"],
    correctIndex: 0,
    explanation: "Aces vs two live but unpaired overcards is a routine ~80/20.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "PREFLOP",
    prompt: "JJ vs AKs",
    heroHand: ["Js", "Jh"],
    villainHand: ["Ad", "Kd"],
    options: ["60 / 40", "55 / 45", "50 / 50", "45 / 55"],
    correctIndex: 1,
    explanation: "A pair still edges suited overcards — JJ stays a slight favorite over AKs, around 55/45.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "PREFLOP",
    prompt: "99 vs AJo",
    heroHand: ["9s", "9h"],
    villainHand: ["Ad", "Jc"],
    options: ["60 / 40", "55 / 45", "50 / 50", "45 / 55"],
    correctIndex: 1,
    explanation: "Middling pair vs two overcards — another near-coinflip with the pair a bit ahead.",
  },

  // --- Flop / turn draw vs. made-hand spots (rule of 2/4, no realistic redraw) ---
  {
    category: "MATCHUP_EQUITY",
    street: "FLOP",
    prompt: "Hero's flush draw vs Villain's flopped set",
    heroHand: ["Ah", "Kh"],
    villainHand: ["Qc", "Qd"],
    board: ["Qh", "7h", "2c"],
    options: ["50 / 50", "40 / 60", "30 / 70", "20 / 80"],
    correctIndex: 1,
    explanation: "9 outs to the nut flush ≈ 36% by the river (rule of 4) — hero's the ~40% underdog here.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "FLOP",
    prompt: "Hero's open-ended straight draw vs Villain's top pair",
    heroHand: ["9c", "8c"],
    villainHand: ["7h", "Kd"],
    board: ["7d", "6h", "2s"],
    options: ["50 / 50", "40 / 60", "30 / 70", "20 / 80"],
    correctIndex: 2,
    explanation: "8 clean outs (any 5 or T) ≈ 32% by the rule of 4 — call it 30/70.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "FLOP",
    prompt: "Hero's gutshot vs Villain's top pair",
    heroHand: ["Jd", "Th"],
    villainHand: ["Qh", "Kd"],
    board: ["Qc", "9s", "2h"],
    options: ["40 / 60", "30 / 70", "20 / 80", "10 / 90"],
    correctIndex: 2,
    explanation: "Only 4 outs (the case 8s) ≈ 16% by the rule of 4.",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "TURN",
    prompt: "Hero's flush draw vs Villain's top pair, one card to come",
    heroHand: ["As", "Ks"],
    villainHand: ["Qh", "Jc"],
    board: ["Qs", "7s", "2d", "4h"],
    options: ["40 / 60", "30 / 70", "20 / 80", "10 / 90"],
    correctIndex: 2,
    explanation: "One card to come halves the outs math — 9 outs ≈ 18% (rule of 2).",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "TURN",
    prompt: "Hero's open-ended straight draw vs Villain's top pair, one card to come",
    heroHand: ["9d", "8d"],
    villainHand: ["7h", "Ad"],
    board: ["7c", "6s", "2h", "3c"],
    options: ["40 / 60", "30 / 70", "20 / 80", "10 / 90"],
    correctIndex: 2,
    explanation: "8 outs with one card to come ≈ 16% (rule of 2).",
  },
  {
    category: "MATCHUP_EQUITY",
    street: "FLOP",
    prompt: "Hero's two overcards vs Villain's underpair",
    heroHand: ["Ac", "Kd"],
    villainHand: ["7d", "7c"],
    board: ["9h", "5s", "2c"],
    options: ["40 / 60", "30 / 70", "20 / 80", "10 / 90"],
    correctIndex: 2,
    explanation: "6 outs (3 live Aces + 3 live Kings) ≈ 24% by the rule of 4.",
  },
];
