import type { DrillQuestion } from "../types.js";

/**
 * Curated out-counting scenarios. Every out count below is verified against the exact cards
 * dealt in the scenario (no card appears twice; every out card is checked to make sure it
 * actually produces the best hand, not a "counterfeit" out that only ties or loses). This is
 * why the category is authored content rather than randomly dealt hands/boards.
 */
export const OUT_COUNTING_SCENARIOS: Array<Omit<DrillQuestion, "id">> = [
  {
    category: "OUT_COUNTING",
    street: "FLOP",
    prompt: "How many outs does Hero have to make the best hand?",
    heroHand: ["Ac", "Ad"],
    villainHand: ["Kh", "Ks"],
    board: ["Kc", "7d", "2h"],
    options: ["1", "2", "4", "8"],
    correctIndex: 1,
    explanation: "Villain flopped a set of Kings. Only the 2 remaining Aces give Hero a bigger set.",
  },
  {
    category: "OUT_COUNTING",
    street: "FLOP",
    prompt: "How many outs does Hero have to the best hand?",
    heroHand: ["Jc", "Tc"],
    villainHand: ["9h", "Ad"],
    board: ["9c", "8c", "2h"],
    options: ["9", "12", "15", "4"],
    correctIndex: 2,
    explanation: "Flush draw (9) + open-ended straight draw (8) minus 2 double-counted cards = 15 outs — a monster combo draw.",
  },
  {
    category: "OUT_COUNTING",
    street: "FLOP",
    prompt: "How many outs does Hero's two pair have to the best hand?",
    heroHand: ["Kd", "Qh"],
    villainHand: ["4h", "4c"],
    board: ["Kc", "Qs", "4d"],
    options: ["1", "2", "4", "8"],
    correctIndex: 2,
    explanation: "Villain flopped bottom set. Hero's two pair needs to boat — 2 more Kings or 2 more Queens, 4 outs total.",
  },
  {
    category: "OUT_COUNTING",
    street: "FLOP",
    prompt: "How many outs does Hero's open-ended straight draw have?",
    heroHand: ["9c", "8c"],
    villainHand: ["7h", "Kd"],
    board: ["7d", "6h", "2s"],
    options: ["4", "6", "8", "9"],
    correctIndex: 2,
    explanation: "Any 5 or T completes the straight — 8 clean outs.",
  },
  {
    category: "OUT_COUNTING",
    street: "FLOP",
    prompt: "How many outs does Hero's gutshot have?",
    heroHand: ["Jd", "Th"],
    villainHand: ["Qh", "Kd"],
    board: ["Qc", "9s", "2h"],
    options: ["2", "4", "8", "9"],
    correctIndex: 1,
    explanation: "Only the case 8 completes this straight — 4 outs.",
  },
  {
    category: "OUT_COUNTING",
    street: "FLOP",
    prompt: "How many outs do Hero's two overcards have to make top pair?",
    heroHand: ["Ac", "Kd"],
    villainHand: ["7d", "7c"],
    board: ["9h", "5s", "2c"],
    options: ["3", "6", "8", "9"],
    correctIndex: 1,
    explanation: "3 live Aces + 3 live Kings = 6 outs to top pair on this dry board.",
  },
  {
    category: "OUT_COUNTING",
    street: "FLOP",
    prompt: "How many outs does Hero's flush draw have?",
    heroHand: ["Qd", "Jd"],
    villainHand: ["Th", "9s"],
    board: ["Td", "4d", "2c"],
    options: ["4", "6", "9", "12"],
    correctIndex: 2,
    explanation: "4 diamonds are already out — 9 more complete the flush.",
  },
  {
    category: "OUT_COUNTING",
    street: "FLOP",
    prompt: "How many outs does Hero's open-ended straight draw have?",
    heroHand: ["6h", "5h"],
    villainHand: ["9h", "Kc"],
    board: ["4c", "3s", "9d"],
    options: ["4", "6", "8", "9"],
    correctIndex: 2,
    explanation: "Any 7 or 2 makes the straight — 8 outs.",
  },
  {
    category: "OUT_COUNTING",
    street: "TURN",
    prompt: "How many outs does Hero's flush draw have with one card to come?",
    heroHand: ["As", "Ks"],
    villainHand: ["Qh", "Jc"],
    board: ["Qs", "7s", "2d", "4h"],
    options: ["4", "6", "9", "12"],
    correctIndex: 2,
    explanation: "4 spades are already out — 9 more make the nut flush.",
  },
  {
    category: "OUT_COUNTING",
    street: "FLOP",
    prompt: "How many outs does Hero have to make quads?",
    heroHand: ["8c", "8d"],
    villainHand: ["Ah", "Kc"],
    board: ["8h", "Ad", "3s"],
    options: ["1", "2", "3", "4"],
    correctIndex: 0,
    explanation: "Hero already flopped a set. Only the last remaining 8 makes quads — 1 out.",
  },
];
