ALTER TABLE `Tournament`
  ADD COLUMN `playFormat` VARCHAR(191) NOT NULL DEFAULT 'FREEZEOUT',
  ADD COLUMN `maxRebuysPerPlayer` INT NOT NULL DEFAULT 0,
  ADD COLUMN `rebuyPeriodMinutes` INT NOT NULL DEFAULT 0;
