import { getPrisma } from "@poker-champ/db";

const CASH_TABLE_BOT_USER_ID_PREFIX = "cash_bot_";

/**
 * The durable economic identity for a cash-table bot, derived from its stable CATALOG id
 * (e.g. "tight_aggressive"), never from a live seat's ephemeral runtime id (PlayerState.id,
 * freshly generated by newBotId() on every single "Add bot"). Mirrors
 * tournaments/tournament-bot-users.ts's getTournamentBotUserId — same convention, same
 * reasoning: `player.id` is the runtime seat identity (changes every add/remove cycle),
 * `player.botId` is the stable catalog identity (set once, shared by every instance of that
 * bot personality). Gifts/Side Bets need a userId, and that userId must be the durable one,
 * or every add-and-interact permanently grows the User table by one row, forever.
 */
export function getCashTableBotUserId(catalogBotId: string): string {
  return `${CASH_TABLE_BOT_USER_ID_PREFIX}${catalogBotId}`;
}

/**
 * Cash-table bots have no backing User row at all — PlayerState.userId is "" (see
 * PlayerLifecycleService.addBot), and hand settlement never touches CashierService/
 * bankrollCents for anyone, bot or human (pot money lives entirely in the live table
 * stack). Gifts/side-bets move User.bankrollCents, and PlayerInteraction.initiatorId/
 * recipientId are real FK columns — a bot recipient needs a real User row or the FK
 * insert fails outright.
 *
 * Lazily upserts one, keyed by getCashTableBotUserId(catalogBotId) — every runtime instance
 * of the same catalog bot (added at any table, any number of times) resolves to the exact
 * same row, bounding total rows to the size of the bot catalog rather than growing per
 * add/remove cycle. Pass the CATALOG id (PlayerState.botId), not the live seat id
 * (PlayerState.id) — the caller is responsible for that distinction, same as
 * ensureTournamentBotUsers callers already are.
 */
export async function ensureCashTableBotUser(catalogBotId: string, botName: string): Promise<void> {
  const prisma = getPrisma();
  const userId = getCashTableBotUserId(catalogBotId);
  await prisma.user.upsert({
    where: { id: userId },
    create: {
      id: userId,
      email: `${userId}@cash-bot.local`,
      passwordHash: "cash_bot",
      displayName: botName,
      role: "USER",
      bankrollCents: 0,
    },
    update: {
      displayName: botName,
    },
  });
}
